services:
  api:
    image: vigneshshettyin/bunky-api:latest
    ports:
      - "8008:8008"
    environment:
      DEBUG: True
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      nginx-proxy-manager_default:
        ipv4_address: 172.18.0.12

networks:
  nginx-proxy-manager_default:
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16